accounting/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounting'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_user_page/$', views.add_user_page, name='add_user_page'),
    url(r'^delete_user_page/$', views.DeleteUser.as_view(), name='delete_user_page'),

    url(r'^(?P<pk>[0-9]+)/DeleteListPage/$', views.DeleteListPage.as_view(), name='DeleteListPage'),
    url(r'^(?P<pk>[0-9]+)/delete_book_page/$', views.DeleteBookPage.as_view(), name='delete_book_page'),
    url(r'^(?P<pk>[0-9]+)/add_book_page/$', views.AddBookPage.as_view(), name='add_book_page'), 
    url(r'^(?P<pk>[0-9]+)/user_book/$', views.UserBook.as_view(), name='user_book'),
    url(r'^(?P<pk>[0-9]+)/book_detail/$', views.BookDetail.as_view(), name='book_detail'), # show all list in a book
    url(r'^(?P<pk>[0-9]+)/AddList/$', views.AddList.as_view(), name='AddList'),
    url(r'^(?P<pk>[0-9]+)/TypeManage/$', views.TypeManage.as_view(), name="type_manage"), # add or delete tpye

    url(r'^func_add_user/$', views.func_add_user, name='add_user_func'),
    url(r'^(?P<list_id>[0-9]+)/func_delete_list/$', views.func_delete_list, name='func_delete_list'),
    url(r'^(?P<user_id>[0-9]+)/func_delete_user/$', views.func_delete_user, name='func_delete_user'),
    url(r'^(?P<user_id>[0-9]+)/func_add_type/$', views.func_add_type, name='func_add_type'),
    url(r'^(?P<user_id>[0-9]+)/func_add_book/$', views.func_add_book, name='func_add_book'),
    url(r'^(?P<book_id>[0-9]+)/func_add_list/$', views.func_add_list, name='func_add_list'),
    url(r'^(?P<book_id>[0-9]+)/func_delete_book/$', views.func_delete_book, name='func_delete_book'),
    url(r'^(?P<type_id>[0-9]+)/func_delete_type/$', views.func_delete_type, name='func_delete_type'),

    #special
    url(r'^(?P<book_id>[0-9]+)/list_in_date/$', views.ListInDate, name='list_in_date'),
    url(r'^(?P<book_id>[0-9]+)/download_data/$', views.save_data, name='save_data'),
    url(r'^(?P<book_id>[0-9]+)/upload_csv_page/$', views.upload_csv_page, name='upload_csv_page'),
    url(r'^(?P<book_id>[0-9]+)/func_upload_csv/$', views.upload_csv, name='func_upload_csv'),
]

bmi/urls.py
from django.conf.urls import url

from . import views

app_name = 'bmi'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^delete_question_page/$', views.DeleteQuestionPage.as_view(), name='delete_question_page'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<pk>[0-9]+)/choice_manage/$', views.ChoiceManage.as_view(), name='choice_manage'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<question_id>[0-9]+)/add_choice/$', views.add_choice, name='add_choice'),
    url(r'^(?P<question_id>[0-9]+)/delete_choice/$', views.delete_choice, name='delete_choice'),
	url(r'^new_question/$', views.new_question, name='new_question'),
	url(r'^add_question/$', views.add_question, name='add_question'),
	url(r'^delete_question/$', views.delete_question, name='delete_question'),
]

bs2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('homepage.urls')),
	url(r'^accounting/', include('accounting.urls')),
    url(r'^bmi/', include('bmi.urls')),
    url(r'^admin/', admin.site.urls),
]

homepage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homepage'
urlpatterns = [
    url(r'^$', views.homepage, name='index'),
]

accounting/models.py
import datetime

from django.db import models
from django.utils import timezone


class User(models.Model):
    user_name = models.CharField(max_length=60)
    founded = models.DateTimeField('date founded')

    def __str__(self):
        return self.user_name

    def was_founded_recently(self):
        return self.founded >= timezone.now() - datetime.timedelta(days=1)


class Pass_book(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_name = models.CharField(max_length=60)
    balance = models.FloatField(default=0)
    founded = models.DateTimeField('data founded')

    def __str__(self):
        return self.book_name

    def was_founded_recently(self):
        return self.founded >= timezone.now() - datetime.timedelta(days=1)

    def set_balance(self, value):
        self.balance = value


class List_type(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type_name = models.CharField(max_length=20)
    type_detail = models.CharField(max_length=500)
    type_for = models.CharField(max_length=20, default="income")

    def __str__(self):
        return self.type_name


class List(models.Model):
    pass_book = models.ForeignKey(Pass_book, on_delete=models.CASCADE)
    list_type = models.ForeignKey(List_type, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=70)
    detail = models.CharField(max_length=500)
    value = models.FloatField(default=0)
    date = models.DateField(default= datetime.date.today)

    def __str__(self):
        return self.list_name

    def set_value(self, val):
        self.value = val

    def get_date(self):
        if(self.date.month >9):
            month = str(self.date.month)
        else:
            month = "0" + str(self.date.month)
        if(self.date.day >9):
            day = str(self.date.day)
        else:
            day = "0" + str(self.date.day)
        year = str(self.date.year)
        date = year + "-" + month + "-" + day
        return date

    def get_year(self):
        return self.date.year

    def get_month(self):
        return self.date.month

    def get_day(self):
        return self.date.day


class Imported_csv(models.Model):
    description = models.CharField(max_length=255, blank=True)
    csv_file = models.FileField(upload_to='./accounting/media/imported_csv/')
    pass_book = models.ForeignKey(Pass_book, on_delete=models.CASCADE, default='1')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

    def get_csv_file(self):
        return str(self.csv_file)

accounting/forms.py
from django import forms
from .models import Imported_csv


class ImportCsvForm(forms.ModelForm):
    class Meta:
        model = Imported_csv
        fields = ('description', 'csv_file', )

bmi/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from .models import Question, choice
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'bmi/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:20]

class DeleteQuestionPage(generic.ListView):
	template_name = 'bmi/delete_question_page.html'
	context_object_name = 'question_list'
	model = Question

class DetailView(generic.DetailView):
    model = Question
    template_name = 'bmi/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'bmi/result.html'

class ChoiceManage(generic.DetailView):
	model = Question
	template_name = 'bmi/choice_manage.html'

def new_question(request):
	return render(request, 'bmi/new_question.html')

def add_question(request):
	question_text = request.POST.get('question_text')
	new_question = Question(question_text=question_text, pub_date=timezone.now())
	new_question.save()
	return HttpResponseRedirect(reverse('bmi:choice_manage', args=(new_question.id,)))

def add_choice(request, question_id):
	new_choice_text = request.POST.get('new_choice')
	question = Question.objects.get(pk=question_id)
	question.choice_set.create(choice_text=new_choice_text, votes=0)
	return HttpResponseRedirect(reverse('bmi:choice_manage', args=(question.id,)))

def delete_choice(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except:
		return render(request, 'bmi/choice_manage.html',{
			 'question':question, 
			 'error_message':"You didn't select a choice.",
			})
	else:
		selected_choice.delete()
	return HttpResponseRedirect(reverse('bmi:choice_manage', args=(question.id,)))

def delete_question(request):
	question = get_object_or_404(Question, pk=request.POST['question_select'])
	choice_all = question.choice_set.all()
	choice_all.delete()
	question.delete()
	return HttpResponseRedirect(reverse('bmi:delete_question_page'))
	
	
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, choice.DoesNotExist):
        return render(request, 'bmi/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('bmi:results', args=(question.id,)))

accounting/templates/accounting/add_book_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
</head>

<body>

<ul class="menu_bar">
    <li class="menu_bar"><a href="{% url 'accounting:user_book' pk=user.id %}">Back to user menu</a></li>
</ul>

<div class="content">
<h1>Add Pass Book</h1>
<form action="{%url 'accounting:func_add_book' user_id=user.id %}" method="post">
{% csrf_token %}
	Pass_Book_name   : <input type="text" name="book_name" size="50" required></input>
	<input type="submit" value="Add">
</form>
</div>
</body>

accounting/templates/accounting/add_list_page.html
<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({
      dateFormat: "yy-mm-dd",
      maxDate: "0",
    });
  } );
  </script>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
</head>

<body>
<ul class="menu_bar">
    <li class="menu_bar"><a href="{% url 'accounting:book_detail' pk=pass_book.id %}">Back to Book menu</a></li>
</ul>

<div class="content">
<h1>Add List</h1>
<form action="{%url 'accounting:func_add_list' book_id=pass_book.id %}" method="post">
{% csrf_token %}
	  List name  : <br>
    <input type="text" name="list_name" size="40" required></input><br>
    Detail   : <br>
    <textarea name="detail" rows="10" cols="50"></textarea><br>
    Value : <input id = val type="number" name="value" min="0" step="0.01" required></input><br>
    type is :<input list="income" name="type_text" required><br>
	<datalist id="income">
        {% for type in pass_book.user.list_type_set.all %}
		    {% if type.type_for == "income" %}
				<option value={{type.type_name}}>
			{% endif %}
		{% endfor %}
	</datalist>
    Date: <input type="text" id="datepicker" name="date" required><br>
    Type_for :
        <input type="radio" name="type_for" value="income">income</input>
        <input type="radio" name="type_for" value="expenses">expenses</input><br>
	<input type="submit" value="Add">
</form>
</div>
</body>

accounting/templates/accounting/add_user_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
</head>

<body>
<ul class="menu_bar">
    <li class="menu_bar"><a href="{% url 'accounting:index' %}">Back to main manu</a></li>
</ul>

<div class="content">
<h1>Add new User</h1>
<form action="{%url 'accounting:add_user_func'%}" method="post">
{% csrf_token %}
	User_name   : <input type="text" name="user_name" size="50" required></input>
	<input type="submit" value="Add">
</form>
</div>
</body>

accounting/templates/accounting/book_detail.html
<head>
  	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  	<link rel="stylesheet" href="/resources/demos/style.css">
  	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  	<script>
  	$( function() {
  	  $( "#datepicker" ).datepicker({
		  dateFormat: "yy-mm-dd",
		  maxDate: "0",
		});
  	} );
  	</script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
</head>


<body>
<ul class="menu_bar">
  <li class="menu_bar"><a href="{% url 'accounting:user_book' pk=pass_book.user.id%}">Back to User manu</a></li>
  <li class="menu_bar"><a href="{% url 'accounting:AddList' pk=pass_book.id %}">Add new List</a></li>
  <li class="menu_bar"><a href="{% url 'accounting:DeleteListPage' pk=pass_book.id %}">Delete List</a></li>
  <li class="menu_bar"><a href="{% url 'accounting:save_data' book_id=pass_book.id %}">Export All Data</a></li>
  <li class="menu_bar"><a href="{% url 'accounting:upload_csv_page' book_id=pass_book.id %}">Import Data [ In This APP Format ]</a></li>
</ul>

<div class="content">
  <h1> This Book Name :  {{pass_book.book_name}} </h1>
  <h2> Your balance is {{pass_book.balance}} </h2>

  <form target='show_list' method="post">
  {% csrf_token %}
  	Select Date: <input type="text" id="datepicker" name="date" required>
  	<input type="submit" value="Show List in date" formAction="{% url 'accounting:list_in_date' book_id=pass_book.id %}">
    <input type="submit" value="Export data in this date" formAction="{% url 'accounting:save_data' book_id=pass_book.id %}">
  </form>
  <center>
  <iframe class="content" src="{% url 'accounting:list_in_date' book_id=pass_book.id %}" name='show_list'></iframe>
  </center>
</div>
</body>

accounting/templates/accounting/book_manage.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:user_book' pk=user.id %}">Back to user menu</a></li>
</ul>

<div class="content">
<h1>Add Pass Book</h1>
<form action="{%url 'accounting:func_add_book' user_id=user.id %}" method="post">
{% csrf_token %}
	Pass_Book_name   : <input type="text" name="book_name" size="50" required></input>
	<input type="submit" value="Add">
</form>
</div>
</body>

accounting/templates/accounting/delete_book_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
    <style>
		th.book{
			width: 65%;
		}
	</style>
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:user_book' pk=user.id %}">Back to user menu</a></li>
</ul>

<div class="content">
<center>
{% if user.pass_book_set.all %}
    <table>
    	<tr>
			<th class="book">Book Name</th>
			<th> Delete </th>
		</tr>
	{% for book in user.pass_book_set.all %}
        <tr>
		    <td>{{book.book_name}}</td>
            <form action="{%url 'accounting:func_delete_book' book_id=book.id %}" method="post">
				{% csrf_token %}
            <td><input type="submit" value="Delete This Book"></td>
            </form>
        </tr>
	{% endfor %}
{% endif %}
</table>
</center>
</div>
</body>

accounting/templates/accounting/delete_list_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
    <style>
		th.list{
			width: 65%;
		}
	</style>
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:book_detail' pk=pass_book.id %}">Back to book menu</a></li>
</ul>

<div class="content">
<center>
{% if pass_book.list_set.all %}
    <table>
    	<tr>
			<th class="list">list Name</th>
			<th>Date</th>
			<th> Delete </th>
		</tr>
	{% for list in pass_book.list_set.all %}
        <tr>
		    <td>{{list.list_name}}</td>
		    <td>{{list.date}}</td>
            <form action="{%url 'accounting:func_delete_list' list_id=list.id %}" method="post">
				{% csrf_token %}
            <td><input type="submit" value="Delete This List"></td>
            </form>
        </tr>
	{% endfor %}
{% endif %}
</table>
</center>
</div>
</body>

accounting/templates/accounting/delete_user_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
    <style>
		th.user{
			width: 65%;
		}
	</style>
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:index' %}">Back to main manu</a></li>
</ul>

<div class="content">
<center>
{% if user_list %}
    <table>
    	<tr>
			<th class="user">User Name</th>
			<th> Delete </th>
		</tr>
	{% for user in user_list %}
        <tr>
		    <td>{{user.user_name}}</td>
            <form action="{%url 'accounting:func_delete_user' user_id=user.id %}" method="post">
				{% csrf_token %}
            <td><input type="submit" value="Delete This User"></td>
            </form>
        </tr>
	{% endfor %}
{% endif %}
</table>
</center>
</div>
</body>

accounting/templates/accounting/frame_show_list.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
    <style>
        th.list{
            width: 60%;
        }
        tr:nth-child(odd){
            background-color: #E9E6E7;
        }

        tr:nth-child(even){
            background-color: #E9E6E7;
        }
        table{
            width:90%;
            border: 2px solid black;
            border-collapse: collapse;
        }
		body{
			background-image: none;
		}
    </style>
</head>

<body>
<center>
<h3>Show List in : {{date_in}}</h3>
{% if pass_book.list_set.all %}
    <table>
    	<tr>
			<th class="list">List Name</th>
			<th>Type</th>
			<th>income</th>
			<th>expenses</th>
		</tr>
	{% for list in pass_book.list_set.all %}
        {% if list.get_date == date_in %}
            {% if list.list_type.type_for == 'income' %}
            <tr>
                <td>{{list.list_name}}</td>
                <td>{{list.list_type}}</td>
                <td style="color:#206F00">{{list.value}}</td>
                <td>-</td>
            </tr>
            {% else %}
            <tr>
                <td>{{list.list_name}}</td>
                <td>{{list.list_type}}</td>
                <td>-</td>
                <td style="color:#B41200">{{list.value}}</td>
            </tr>
            {% endif %}
        </tr>
        {% endif %}
	{% endfor %}
{% endif %}
</table>
</center>
</body>

accounting/templates/accounting/index.html
<head>
    {% load static %}
    <link id="pagestyle" rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
	<style>
		th.user{
			width: 65%;
        }
	</style>
    <script>
    function swapStyleSheet(){
        document.getElementById('pagestyle').setAttribute('href', "{% static 'accounting/theme2/main_style.css' %}");
    }
    </script>

</head>

<body>
<ul class="menu_bar">
    <li class="menu_bar" style="float:right"><a href="{% url 'homepage:index' %}">Go To Homepage</a></li>
	<li class="menu_bar"><a href="{% url 'accounting:add_user_page' %}">ADD NEW USER</a></li>
	<li class="menu_bar"><a href="{% url 'accounting:delete_user_page' %}">DELETE USER</a></li><br><br>
</ul>

<div class="content">
<center>
<h1> Welcome </h1>
<h2> Choise you account or add new account </h2>

{% if user_list %}
    <table>
    	<tr>
			<th class="user">User Name</th>
			<th>founded</th>
		</tr>
	{% for user in user_list %}
        <tr>
		    <td><a href="{% url 'accounting:user_book' pk=user.id %}">{{user.user_name}}</a></td>
            <td style="text-align:center">{{user.founded}}</td>
        </tr>
	{% endfor %}
{% endif %}
</table>
</center>
<button onclick="swapStyleSheet()">change theme</button>
</div>
</body>

accounting/templates/accounting/type_manage.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
	<style>
		th.detail{
			width: 70%;
		}
	</style>
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:user_book' pk=user.id %}">Back to User book</a></li>
</ul>

<div class="content">
<h2> If you delete any type list which have type like that must be lost !! </h2>
<br>
<center>
{% if not user.list_type_set.all %}
	<h1> May be you should make new list type? </h1>
{% endif %}
    <table>
    	<tr>
			<th>Type Name</th>
			<th class="detail">Detail</th>
			<th>for</th>
			<th>function</th>
		</tr>
		<form action="{%url 'accounting:func_add_type' user_id=user.id %}" method="post">
		{% csrf_token %}
			<td><input type="text" name="type_name" size="25" required></input></td>
    		<td><input type="text" name="detail" size="60"></input></td>
    		<td><select name="type_for">
    		    <option value="income">Income</option>
            	<option value="expenses">Expenses</option>
            	</select></td>
            <td><input type="submit" value="Make New Type"></td>
		</form>

	{% for type in user.list_type_set.all %}
        <tr>
            <td>{{type.type_name}}</td>
            <td>{{type.type_detail}}</td>
            <td style="text-align:center">{{type.type_for}}</td>
            <form action="{%url 'accounting:func_delete_type' type_id=type.id %}" method="post">
				{% csrf_token %}
            <td><input type="submit" value="Delete This Type"></td>
			</form>
        </tr>
	{% endfor %}
</table>
</center>
</div>
</body>

accounting/templates/accounting/upload_csv_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
    <style>
        th.date{
            width: 5%
        }
        th.detail{
            width: 25%
        }
        th.type_for{
			width: 10%
		}
    </style>
</head>

<body>

<ul class="menu_bar">
    <li class="menu_bar"><a href="{% url 'accounting:book_detail' book_id %}">Back to Book menu</a></li>
</ul>

<div class="content">
  <h1> Please check you format , it should seem like this </h1>

   <p> Income Exam </p>
   <table>
    	<tr>
			<th class='date'>Year</th>
			<th class='date'>Month</th>
			<th class='date'>Day</th>
			<th class='detail'>Detail</th>
            <th class='detail'>Type</th>
            <th class='type_for'>Income</th>
            <th class='type_for'>Expenses</th>
		</tr>
        <tr>
            <td>2017</td>
            <td>2</td>
            <td>27</td>
            <td>ถอนเงินจากธนาคาร</</td>
            <td>ถอนเงิน</</td>
            <td>500</td>
            <td></td>
        </tr>
  </table>

   <p> Expenses Exam </p>
   <table>
    	<tr>
			<th class='date'>Year</th>
			<th class='date'>Month</th>
			<th class='date'>Day</th>
			<th class='detail'>Detail</th>
            <th class='detail'>Type</th>
            <th class='type_for'>Income</th>
            <th class='type_for'>Expenses</th>
		</tr>
        <tr>
            <td>2017</td>
            <td>2</td>
            <td>27</td>
            <td>ซื้อเลย์</td>
            <td>ขนม</td>
            <td></td>
            <td>50</td>
        </tr>
  </table>

  <form method="post" action="{% url 'accounting:func_upload_csv' book_id %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
</div>
</body>

accounting/templates/accounting/user_book_page.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounting/theme1/main_style.css' %}" />
	<style>
		th.book{
			width: 75%;
		}
	</style>
</head>

<body>
<ul class="menu_bar">
	<li class="menu_bar"><a href="{% url 'accounting:index' %}">Back to main manu</a></li>
	<li class="menu_bar"><a href="{% url 'accounting:add_book_page' pk=user.id %}">ADD NEW PASS_BOOK</a></li>
	<li class="menu_bar"><a href="{% url 'accounting:delete_book_page' pk=user.id %}">Delete PASS_BOOK</a></li>
	<li class="menu_bar"><a href="{% url 'accounting:type_manage' pk=user.id %}">Go to Type manage</a></li>
</ul>

<div class="content">
<h1> HI {{user.user_name}} </h1>
<br><br>
<center>
{% if user.pass_book_set.all %}
    <table>
    	<tr>
			<th class="book">Book Name</th>
			<th>Balance</th>
		</tr>
	{% for book in user.pass_book_set.all %}
        <tr>
		    <td><a href="{% url 'accounting:book_detail' pk=book.id%}">{{book.book_name}}</a></td>
            <td style="text-align:center">{{book.balance}}</td>
        </tr>
	{% endfor %}
{% endif %}
	</table>
</center>
</div>
</body>